src/pages/Sketchbook/Sketchbook.jsx
Fix: #7
The button has been added. Now a stage can be cleared with one click.
=> fix: added clear button

package-lock.json, package.json, src/pages/Sketchbook/Sketchbook.jsx
The following fixes have been done
1. Added brush color , Fix #8 
2. Added brush width selector Fix #14  
3. Added save options for png, jpg, pdf. Fix #9
=> Added Brush color, size, save option

src/pages/Sketchbook/Sketchbook.jsx
Fix #5
@ItsRoy69 I think it's a good idea to add Prettier dependency and create config file to define formatting rules for everyone. I will create an issue addresing it.
=> fix: undo button

src/pages/Sketchbook/Sketchbook.jsx
Fix: #6
Work for cases:
- undo/redo
- when draw -> undo -> draw, redo history will be cleared
- after clear, redo returns the entire array of previously drawn lines
=> Redo button

.prettierignore, .prettierrc, package-lock.json, package.json
Fix: #22
Prettier should now work and the coding style rules should be the same for everyone.
=> prettier dependency and config files

index.html, src/pages/Sketchbook/Sketchbook.jsx
Issue #27 
Eraser added.
The size of the eraser can be adjusted by adjusting the brush size!
=> Eraser added successfully.

package-lock.json, package.json, src/pages/Sketchbook/Sketchbook.jsx
Fix: #26 
Tool buttons are smaller and still represent button functionality.
=> added react icons library and put icons inside buttons

src/pages/Sketchbook/Sketchbook.jsx
Fixes - #34
Please add KWOC tag! thank you!
=> Fix: color not change

src/App.jsx, src/Darkmode/Darkmode.jsx, src/constants/Navbar/Navbar.jsx, src/pages/Authentication/Register.jsx
For Desktop View
For Mobile View
=> fixed the position of Darkmode

.all-contributorsrc, README.md, package.json, workflow.md
Closes issue #4
Hey @ItsRoy69 , you can close the other 2 PRs and add this one. It has everything. 
I have made a separate workflow.md and linked it in readme. Also add the iwoc24 tag, difficulty level(medium would be appreciated as I added the contributors manually), before merging with me assigned. Thankyou for your suggestion, happy contributions !
=> feature : readme and workflow.md updated

package-lock.json, package.json, src/App.jsx, src/pages/Blog/Blog.jsx
This PR resolves issue #59
This pull request addresses the 
design as outlined in the provided specifications. The changes encompass various visual and functional enhancements, aligning with the design requirements to create a seamless and visually appealing user experience.
./pages/Blog
./pages/Blog/Blog.jsx
This PR enhances the project's contribution guidelines by automating the validation of PR titles, ensuring adherence to conventional commit prefixes. Contributions and feedback are encouraged for continuous improvement.
@ItsRoy69 please review this PR.
Thanks
**
=> fix : Created Blog Page

src/components/JoinUs/joinus.css, src/pages/Home/home.css
What does this PR do?
Fixes #80
=> fix :  'Join Us' section as it overlaps the navbar section 

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/docs.yaml, .github/ISSUE_TEMPLATE/other.yaml, .github/ISSUE_TEMPLATE/website.yaml
Issue: https://github.com/WikiPortal/DoodleCollab/issues/2
=> fix: Created issue template for fix types

.github/workflows/greetings.yml
=> build: Greetings action added

src/constants/Navbar/navbar.css
Resolved a bug where the slider inside the toggle button was moving outside the designated bounds. This fix ensures a consistent and visually appealing user experience.
=> fix: #101- Ensure Toggle Button Slider Stays Within Bounds

src/components/About/HomeAbout.jsx, src/components/Banner/HomeBanner.jsx, src/components/Banner/homebanner.css
=> style: home page added

.github/workflows/greetings.yml
=> bug: greetings.yml corrected

src/pages/Features/Features.jsx
=> fix: Features tab navbar margin

src/components/About/HomeAbout.jsx, src/components/About/homeabout.css
This pull request addresses the static appearance of the home page cards by introducing dynamic hover effects and colored borders. The current lack of interactivity can be enhanced to improve user experience and visual aesthetics. The proposed changes aim to create a more engaging design that is consistent across both dark and light modes.
1. Add a subtle and visually pleasing hover effect to provide feedback to users.
2. Implement colored borders for the cards during the hover state to enhance the dynamic appearance.
3. Ensure consistent and visually appealing hover effects and colored borders in both dark and light modes.
https://github.com/WikiPortal/DoodleCollab/assets/130365071/4f5d1deb-7ef0-43ab-bd97-7df8782f3d2b
- Test the implemented hover effects and colored borders across …
=> style: add hover effects to cards on home page

src/pages/Authentication/Login.jsx, src/pages/Authentication/auth.css
=> fix: 🚀 Improved the Login Page

src/constants/Footer/Footer.jsx
Added relevant links to social media icons in the footer section.
=> add links to footer

src/constants/Navbar/Navbar.jsx, src/pages/Authentication/Register.jsx, src/pages/Authentication/auth.css
**Registration Page Initially**
1. The image has been given proper margin and border radius, without cropping it.
2. In dark mode, **the input text is in white color**, with the same color applied to the input text box. Now, it is visible, and the issue has been rectified.
1. The Github link in navbar is in the wrong position.
2. There is extra margin for the Name input boxes at their top, bottom, and left.
3. There is improper space alignment for the password description and the policy agreement checkbox.
4. Forms have been made scrollable.
These issues also have been rectified.
**Modified Registration Page**
=> Fix: UI bugs had been rectified in Registration Page

src/App.jsx, src/constants/Notification/Toast.jsx, src/context/AppContext.jsx, src/pages/Authentication/Login.jsx, src/pages/Authentication/Register.jsx
- Added a custom toast notification component that displays success and error messages. 
- This toast notification is designed to last for 5 seconds and can be used throughout the application. I've also created a context (`AppContext`) to manage the state of the toast and make it easily accessible across components.
- Added `showToast` method to `AppContext` to trigger the display of toast messages.
- Added`Toast` component.
- ### Login with Invalid credentials 
- ### Login with valid credentials 
- ### Register with Invalid credentials 
- ### Register with valid credentials
=> Custom toast notification

.github/workflows/author-assign.yml
This PR resolves the issue #159 
**Description:**
This pull request addresses the need for a streamlined process by introducing an automated workflow to assign the pull request author as the assignee. This enhancement ensures that the person initiating the changes is automatically assigned, simplifying the assignment process.
**Proposed Changes:**
Introduce a GitHub Action that automatically assigns the pull request author as an assignee when a new pull request is created.
**Expected Behavior:**
Upon creating a pull request, the GitHub Action will automatically assign the pull request author, enhancing the efficiency of the assignment process.
**Files added**
- `.github/workflows/author-assign.yml`
@ItsRoy69 please review this PR.
Thanks
=> feat: add workflow for author assign

src/components/Banner/HomeBanner.jsx, src/components/Banner/homebanner.css, src/components/Faq/Faq.jsx, src/components/TrustDevelopers/TrustDevelopers.jsx, src/components/TrustDevelopers/trustdevelopers.css, src/constants/Footer/Footer.jsx
this pull request addresses the accessibility issue of this project ( main page ) ( #174 )
I made the necessary changes to achieve the highest amount of accessibility for this application ( main page ) as you can explore in the current source code or take a look at the screenshot below
**BEFORE ----------------------------------------------------------------------------------------------------------------------**
**AFTER --------------------------------------------------------------------------------------------------------------------------**
=> Accessibility of home page  is 100% now

.eslintrc.cjs, package-lock.json, package.json, src/index.css, src/lib/utils.js, src/pages/Sketchbook/Sketchbook.jsx, src/pages/Sketchbook/data.jsx
Closes #93
Changes:
1. Redesigned the sketch book menu bar 
2.  fixed the bug of color picker not working properly
3.  Highlighting the active tool
4.  Increases the brush size to 50 as the larger values are useful specially for the eraser
Issue #93
=> refactor: revamp the sketchbook tools menu bar

src/constants/Navbar/Navbar.jsx, src/context/AppContext.jsx, src/pages/Authentication/Login.jsx, src/pages/Sketchbook/Sketchbook.jsx
**Related issue**
This PR resolved the issue #88 
**Description:**
This pull request adds the `isLoggedIn` state into the `AppContext` and also the `updateLoggedIn()` to update the logged in state from the navbar button.
**Proposed Changes:**
Make changes to AppContext to track the log in state. The `updateLoggedIn()` will change the logged in state based on the boolean passed in. `True` will validate the token from local storage and set the `isLoggedIn` to `true`. On the other hand, `false` will clear the token from local storage and set the `isLoggedIn` to `false`.
**Expected Behaviour:**
These changes will change the behaviour of the `Sign Up` button in the nav bar. Once the user is logged the `Sign Up` button will change to `Sign Out` and when the user clicks the `Sign Out` button, …
=> feat: add sign out functionality

package-lock.json, package.json, screen-recording-app/package.json, src/pages/Sketchbook/ScreenRecording.jsx, src/pages/Sketchbook/Sketchbook.jsx
Issue Number : #161 
Added the feature, and can share it using email
=> Screen Recording Feature added

src/components/About/homeabout.css, src/components/Banner/homebanner.css, src/components/TrustDevelopers/trustdevelopers.css
I have solved the problem of dark mode writing colors  for issue #189 under WoC 2024
=> Dark mode color problem solved

src/components/Banner/HomeBanner.jsx, src/constants/Navbar/Navbar.jsx, src/pages/Authentication/Login.jsx, src/pages/Authentication/Register.jsx, src/pages/Authentication/auth.css
=> Show loading spinner on loading state in the button of login and register form

package-lock.json, src/layouts/Root.jsx, src/pages/Sketchbook/Sketchbook.jsx, src/pages/Sketchbook/sketchbook.css
Updated Sketchbook height to be fixed.  issue No #199
=> fix: sketchbook height

package-lock.json, package.json, src/pages/Sketchbook/Sketchbook.jsx
Screenshot
fix - implemented the image upload feature and on uploading the image will appear on the canvas.
fixed issue #182
=> fix: implemented the image upload feature #182

package-lock.json, package.json, server/.gitignore, server/db/index.js, src/components/Banner/HomeBanner.jsx, src/components/UserProfile/UserProfile.jsx, src/pages/Authentication/Login.jsx, src/pages/Authentication/Register.jsx, src/pages/Features/Features.jsx, src/pages/Sketchbook/Sketchbook.jsx, src/pages/Sketchbook/data.jsx, src/routes/PrivateRoute.jsx
hey @ItsRoy69 
removed all MUI components and fixed mongoose URL issue too
Thank You...!!
=> Revamp css2
